version: "3"

services:
  redis:
    image: redis:alpine
    container_name: ${INSTANCE_NAME}_redis
    restart: "no"
    networks:
      - hashfrog

  hashfrog:
    image: elwafo/hashfrog:latest
    container_name: ${INSTANCE_NAME}_hashfrog
    restart: "no"
    ports:
      - "${PORT}:3000"
    networks:
      - hashfrog
    environment:
      - REDIS_HOST=${INSTANCE_NAME}_redis

networks:
  hashfrog:

