version: "3"

services:
  redis:
    image: redis:alpine
    container_name: ${INSTANCE_NAME}_redis
    restart: "no"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - hashfrog

networks:
  hashfrog:

volumes:
  hashfrogdb:

